source $HOME/.zsh/powerlevel10k/powerlevel10k.zsh-theme
POWERLEVEL9K_MODE='awesome-fontconfig'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable rbenv anaconda vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs command_execution_time)
DEFAULT_USER=soeren

POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='235'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='007'
POWERLEVEL9K_DIR_HOME_BACKGROUND=$POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND
POWERLEVEL9K_DIR_HOME_FOREGROUND=$POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='159'

# POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='232'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='252'

POWERLEVEL9K_STATUS_OK_BACKGROUND='235'
#POWERLEVEL9K_STATUS_OK_FOREGROUND='252'
#source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
